### ISSUE TITLE
Expand particular cell

### ISSUE THREAD

**Issue by khushDesai** [okhanokbay/ExpyTableView#10]
hello @okhanokbay, i want to expand particular cell on alert how can i achieve it please help.!
Thank you :)

**Comment by okhanokbay** [comment]
Hi @khushDesai , sorry but I didn't understand the part you say "on alert"? 

Maybe you want to use these methods?:

 ```swift
  public func expand(_ section: Int) {}
  public func collapse(_ section: Int) {}

  //Use as below.
  expandableTableView.expand(1) //Expand section at (index: 1) manually
  expandableTableView.collapse(0) //Collapse section at (index: 0) manually
```

**Comment by khushDesai** [comment]
@okhanokbay Thank you , now its worked. :) 👍
