### ISSUE TITLE
@objc - objective c support

### ISSUE THREAD

**Issue by JulesMoorhouse** [okhanokbay/ExpyTableView#11]
Please will you add the @objc attribute to provide objective c support

**Comment by okhanokbay** [comment]
Thanks for suggestion. I will add this to a milestone asap.
Also if you want to add this and submit a PR with an example project included, it will be appreciated :)

**Comment by lorenzoPrimi** [comment]
@okhanokbay was this implemented or it's time I learn swift? 😄

**Comment by lorenzoPrimi** [comment]
I'm working on this: https://github.com/lorenzoPrimi/ExpyTableView/tree/support/obj-c

**Comment by okhanokbay** [comment]
Hey @lorenzoPrimi, this isn't implemented but great to see you working on it, thanks :)

**Comment by lorenzoPrimi** [comment]
https://github.com/okhanokbay/ExpyTableView/pull/18

**Comment by okhanokbay** [comment]
This won't be added for now
