### ISSUE TITLE
Simple example expands less items than returned by delegate

### ISSUE THREAD

**Issue by alexandre-g** [okhanokbay/ExpyTableView#12]
```
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
		return 4
}
```
But sections expand to 3 rows :/

**Comment by okhanokbay** [comment]
Sections are being expanded and collapsed when you use ExpyTableView.

The cell instance that you return from `expandableCellForSection:` data source method is actually the first row of belonged section. Thus, when you return 4 from `numberOfRowsInSection` data source method, first row refers to expandable cell and the other 3 rows refer to other rows in this section.

So, it is the desired result and it is not the number of rows that will expand, it is the number of the rows in section including expandable cell.

In a future version, this situation will be more clear by little changes.

**Comment by alexandre-g** [comment]
Hi, thanks for the prompt reply. Thought it was a bug as was first confused trying to implement with one of the sections being non expandable - and the delegate not asking for it as I didn't have the `canExpand` method, so had the first row missing. Then tried with the Basic example and had that. More clear now and after reading the code comments, but perhaps would be good to add some of these intricacies into the readme at some point before it's more clear implementation wise.
