### ISSUE TITLE
Set header multiline text?

### ISSUE THREAD

**Issue by Ligament** [okhanokbay/ExpyTableView#13]
I want to set  header multiline in header expand and in set 
`cell.labelName.numberOfLines = 0
  cell.labelName.lineBreakMode = .byWordWrapping`
is not multiline. And I want this header to be automatically height based on the number of lines.

**Comment by okhanokbay** [comment]
Are you setting the contraints in the right way? 
Are you setting `UITableViewAutomaticDimension` for `tableViewRowHeight`?
Can you share a sample project that reproduces this since I cant? @Ligament

**Comment by okhanokbay** [comment]
Closing this because I can't reproduce the issue.
