### ISSUE TITLE
Support Swift 4

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [okhanokbay/ExpyTableView#15]
Will you be providing support for Swift 4?

**Comment by okhanokbay** [comment]
Yes, very soon. @vaibhav-varshaaweblabs

**Comment by vaibhav-varshaaweblabs** [comment]
@okhanokbay Can you please share the timeframe? As we are developing an App using your library and we are on a tight schedule

**Comment by okhanokbay** [comment]
Adding this to milestone 0.4.1 but not sure when it will be completed since Im working on it only in my free time.

**Comment by moazkh60** [comment]
@okhanokbay any updates? I think you stopped maintaining this library. Please upgrade it to swift4 if you can.

**Comment by okhanokbay** [comment]
No updates yet, sorry. Swift 4 support will be added in a week or so. @moazkh60

**Comment by okhanokbay** [comment]
FYI: Swift 4.0 is now being supported in v1.0
