### ISSUE TITLE
What's the point of [weak self] on some closures?

### ISSUE THREAD

**Issue by sheinix** [okhanokbay/ExpyTableView#21]
Hi, I'm trying to use the library in my project with Swift4. I have noticed a few `[weak self]` in closures that don't make any difference as the closure is not held by `self` itself, like in the DispatchQueue. Is there a reason for this?
Example:
```
DispatchQueue.main.async { [weak self] _ in
			if self?.visibleSections[indexPath.section] == true {
				....
		}
```

**Comment by okhanokbay** [comment]
No, there is no reason, it makes no difference and should not be there.
