### ISSUE TITLE
Error when adding just files and not using cocoapods

### ISSUE THREAD

**Issue by RogelioHIT** [okhanokbay/ExpyTableView#26]
i believe the error is because in the file ExpyAbstractions.swift the import is for Foundation instead of UIKit.
I changed the import and it's working fine now

**Comment by okhanokbay** [comment]
Thanks! Will update this soon.

**Comment by RogelioHIT** [comment]
Hi, thanks for the fast response, i change the update and it's compiling now, but it i can't make it work, there is a difference between just adding the files and cocoapods way?

edit: there is a kind of warning in the console, it says the following `Unknown class _TtC13ExpyTableView13ExpyTableView in Interface Builder file.`

edit 2: I use cocoapods and my code works fine, but i really don't want to use cocoapods, also , i checked the file ExpyAbstractions.swift downloaded by cocoapods, and it has also the line
`import Foundation` but there is no error
