### ISSUE TITLE
Unexpadable section collapses.

### ISSUE THREAD

**Issue by jombie** [okhanokbay/ExpyTableView#27]
I have two sections in table view with first section having only one item and second section having multiple (header, detail) items. When any item in second section is expanded the first section expands and collapses simultaneously causing fluctuation in scroll. Any idea how to solve the same.

**Comment by okhanokbay** [comment]
Are you able to reproduce this with ExpyTableView example projects? 
If not, can you please share some code or an example project that is reproducing this? (you can use the ExpyTableView example projects and modify them if you want) @jombie

**Comment by okhanokbay** [comment]
Closing due to no response. Please reopen if you need any further dialog.
