### ISSUE TITLE
expyState automatically expand and collapse

### ISSUE THREAD

**Issue by vanillatte09** [okhanokbay/ExpyTableView#30]
Hi, just trying to use your project. but my tableview always automatically expand and collapse (the expand even didn't show its item) whenever i click the section. Is there any wrong with that? i've been following and study your example as well

![expystate](https://user-images.githubusercontent.com/15572748/42087834-a2af82ea-7bc1-11e8-8825-3017f01452c4.PNG)

**Comment by okhanokbay** [comment]
I think this should be related to your own implementation since the example projects are working properly. The code you shared is not enough to have any clue about your implementation.

**Comment by vanillatte09** [comment]
sorry, yes it's my mistake. because i set manual expand. thank youuu
