### ISSUE TITLE
Selecting specific row under specific section

### ISSUE THREAD

**Issue by zishanj** [okhanokbay/ExpyTableView#34]
Is there any supporting function that selects specific row under specific section? It should auto scroll to specific section, expand it and then select specific row updating the scroll position.

**Comment by okhanokbay** [comment]
There is no supporting function that does all of these functionalities at the same time, but:

You can auto-scroll to a specific section by using UITableView methods like `scrollToRowAtIndexPath`.
Then you can expand that section by using ExpyTableView's `expand` method.
Then you can select any cell in that section by using native `selectRowAtIndexPath`.

I think, if something can be wrapped up with combination of already-written methods then it's not a good thing to add that functionality to the base of a shared component. So I don't foresee `ExpyTableView` will have this in future.
