### ISSUE TITLE
Codebase is old Swift version (4.0; current is 5.1)

### ISSUE THREAD

**Issue by starlight173** [okhanokbay/ExpyTableView#36]
Please support Swift 4.2 on CocoaPod.

**Comment by lucatk** [comment]
I was able to fix this (temporarily) by changing "Swift Compiler - Language" to Swift 4 in Build Settings for ExpyTableView target in Pods project. After that manually build the project once using ExpyTableView scheme.

**Comment by starlight173** [comment]
@okhanokbay could you push the update to Pod ?

**Comment by okhanokbay** [comment]
Sorry for being tooooo late 😞 updated
