### ISSUE TITLE
Hello I found one problem that when I expand tableview but unable to collpased

### ISSUE THREAD

**Issue by bave233** [okhanokbay/ExpyTableView#40]
This is the error log that debug to me

how to reproduce is just scroll and expand that its..

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003ef3d40 UIView:0x7fdcb112bf00.height == 15   (active)>",
    "<NSLayoutConstraint:0x600003eedc70 UIStackView:0x7fdcadc6f510.height == 66   (active)>",
    "<NSLayoutConstraint:0x600003eece10 'UISV-canvas-connection' UIStackView:0x7fdcadc6f510.top == UIView:0x7fdcb112bf00.top   (active)>",
    "<NSLayoutConstraint:0x600003eef8e0 'UISV-canvas-connection' V:[UIView:0x7fdcade60cb0]-(0)-|   (active, names: '|':UIStackView:0x7fdcadc6f510 )>",
    "<NSLayoutConstraint:0x600003eed400 'UISV-fill-equally' UIView:0x7fdcade820b0.height == UIView:0x7fdcb112bf00.height   (active)>",
    "<NSLayoutConstraint:0x600003eed0e0 'UISV-fill-equally' UIView:0x7fdcade60cb0.height == UIView:0x7fdcb112bf00.height   (active)>",
    "<NSLayoutConstraint:0x600003eece60 'UISV-spacing' V:[UIView:0x7fdcb112bf00]-(5)-[UIView:0x7fdcade820b0]   (active)>",
    "<NSLayoutConstraint:0x600003eed040 'UISV-spacing' V:[UIView:0x7fdcade820b0]-(5)-[UIView:0x7fdcade60cb0]   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003ef3d40 UIView:0x7fdcb112bf00.height == 15   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-03-16 17:27:59.271736+0700 True Smart Merchant[79627:2566823] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003ef5d60 UIView:0x7fdcade820b0.height == 15   (active)>",
    "<NSLayoutConstraint:0x600003eedc70 UIStackView:0x7fdcadc6f510.height == 66   (active)>",
    "<NSLayoutConstraint:0x600003eece10 'UISV-canvas-connection' UIStackView:0x7fdcadc6f510.top == UIView:0x7fdcb112bf00.top   (active)>",
    "<NSLayoutConstraint:0x600003eef8e0 'UISV-canvas-connection' V:[UIView:0x7fdcade60cb0]-(0)-|   (active, names: '|':UIStackView:0x7fdcadc6f510 )>",
    "<NSLayoutConstraint:0x600003eed400 'UISV-fill-equally' UIView:0x7fdcade820b0.height == UIView:0x7fdcb112bf00.height   (active)>",
    "<NSLayoutConstraint:0x600003eed0e0 'UISV-fill-equally' UIView:0x7fdcade60cb0.height == UIView:0x7fdcb112bf00.height   (active)>",
    "<NSLayoutConstraint:0x600003eece60 'UISV-spacing' V:[UIView:0x7fdcb112bf00]-(5)-[UIView:0x7fdcade820b0]   (active)>",
    "<NSLayoutConstraint:0x600003eed040 'UISV-spacing' V:[UIView:0x7fdcade820b0]-(5)-[UIView:0x7fdcade60cb0]   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003ef5d60 UIView:0x7fdcade820b0.height == 15   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by okhanokbay** [comment]
AFAIS, this is your own view debug log. Please refer to example project for the complete working edition.
