### ISSUE TITLE
Compile errors in iOS 13.4

### ISSUE THREAD

**Issue by daviddelmonte** [okhanokbay/ExpyTableView#42]
Hi, I'm getting compile errors using Xcode Version 11.4 (11E146), on iOS 13.4. The error is:

`/ExpyTableView/BasicExampleViewController.swift:30:1: Non-'@objc' method 'tableView(_:canExpandSection:)' does not satisfy requirement of '@objc' protocol 'ExpyTableViewDataSource'`

Please advise. Many thanks

**Comment by okhanokbay** [comment]
on it

**Comment by daviddelmonte** [comment]
Wonderful , Thank you

**Comment by okhanokbay** [comment]
thanks for reporting, fixed
